### ISSUE TITLE
Not so much an issue but maybe an improvement

### ISSUE THREAD

**Issue by richnz** [yusufugurozbek/angular-google-analytics#1]
Hi,

Firstly big thanks, this really helped me to sort my gtag issue with how to set the url from angular. :-)

I assume that you have used a script file so you can easily access the gtag function.
One syntax i've found that can make this simpler is to use the following : 
`(<any>window)`
This means that the whole code can exist inside the app.component.ts like so:
``` typescript
if (event instanceof NavigationStart) {
   const url = event['url'];
   if (url !== null && url !== undefined && url !== '' && url.indexOf('null') < 0) {
      (<any>window).gtag('config',` environment.googleAnalyticsID , { 'page_path': url });
   }
}
```

Just wanted to share in case you weren't aware (oh also you might notice i'm using an environment variable as a bit of syntactical sugar). 

Thanks again, much appreciated.

**Comment by yusufugurozbek** [comment]
Many thanks for your issue. I just updated the project and committed what you want.
